//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleStatefulMathClient.MathService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MathService.IMathServiceStateful")]
    public interface IMathServiceStateful {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMathServiceStateful/StartWorkflow", ReplyAction="http://tempuri.org/IMathServiceStateful/StartWorkflowResponse")]
        void StartWorkflow();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMathServiceStateful/DivideNumbers", ReplyAction="http://tempuri.org/IMathServiceStateful/DivideNumbersResponse")]
        double DivideNumbers(double dividend, double divisor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMathServiceStateful/GetLastQuotient", ReplyAction="http://tempuri.org/IMathServiceStateful/GetLastQuotientResponse")]
        double GetLastQuotient();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMathServiceStateful/StopWorkflow", ReplyAction="http://tempuri.org/IMathServiceStateful/StopWorkflowResponse")]
        void StopWorkflow();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IMathServiceStatefulChannel : ConsoleStatefulMathClient.MathService.IMathServiceStateful, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class MathServiceStatefulClient : System.ServiceModel.ClientBase<ConsoleStatefulMathClient.MathService.IMathServiceStateful>, ConsoleStatefulMathClient.MathService.IMathServiceStateful {
        
        public MathServiceStatefulClient() {
        }
        
        public MathServiceStatefulClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MathServiceStatefulClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MathServiceStatefulClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MathServiceStatefulClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void StartWorkflow() {
            base.Channel.StartWorkflow();
        }
        
        public double DivideNumbers(double dividend, double divisor) {
            return base.Channel.DivideNumbers(dividend, divisor);
        }
        
        public double GetLastQuotient() {
            return base.Channel.GetLastQuotient();
        }
        
        public void StopWorkflow() {
            base.Channel.StopWorkflow();
        }
    }
}
