//--------------------------------------------------------------------------------
// This file is part of the downloadable code for the Apress book:
// Pro WF: Windows Workflow in .NET 3.5
// Copyright (c) Bruce Bukovics.  All rights reserved.
//
// This code is provided as is without warranty of any kind, either expressed
// or implied, including but not limited to fitness for any particular purpose. 
// You may use the code for any commercial or noncommercial purpose, and combine 
// it with your own code, but cannot reproduce it in whole or in part for 
// publication purposes without prior approval. 
//--------------------------------------------------------------------------------

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharedWorkflows {
    using System;
    using System.ComponentModel;
    using System.Workflow.Activities;
    using System.Workflow.ComponentModel;
    using System.Workflow.ComponentModel.Design;
    using System.Workflow.ComponentModel.Compiler;
    
    
    [ToolboxItemAttribute(typeof(ActivityToolboxItem))]
    public partial class GuessReceived : HandleExternalEventActivity {
        
        public static DependencyProperty EProperty = DependencyProperty.Register("E", typeof(SharedWorkflows.GuessReceivedEventArgs), typeof(GuessReceived));
        
        public GuessReceived() {
            base.InterfaceType = typeof(SharedWorkflows.IGuessingGame);
            base.EventName = "GuessReceived";
        }
        
        [BrowsableAttribute(false)]
        [DesignerSerializationVisibilityAttribute(DesignerSerializationVisibility.Hidden)]
        public override System.Type InterfaceType {
            get {
                return base.InterfaceType;
            }
            set {
                throw new InvalidOperationException("Cannot set InterfaceType on a derived HandleExternalEventActivity.");
            }
        }
        
        [BrowsableAttribute(false)]
        [DesignerSerializationVisibilityAttribute(DesignerSerializationVisibility.Hidden)]
        public override string EventName {
            get {
                return base.EventName;
            }
            set {
                throw new InvalidOperationException("Cannot set EventName on a derived HandleExternalEventActivity.");
            }
        }
        
        [ValidationOptionAttribute(ValidationOption.Required)]
        public SharedWorkflows.GuessReceivedEventArgs E {
            get {
                return ((SharedWorkflows.GuessReceivedEventArgs)(this.GetValue(GuessReceived.EProperty)));
            }
            set {
                this.SetValue(GuessReceived.EProperty, value);
            }
        }
        
        protected override void OnInvoked(System.EventArgs e) {
            this.E = ((SharedWorkflows.GuessReceivedEventArgs)(e));
        }
    }
}
